name: user_project_wrapper

outputs:
  - design.lvs.v
  - design_merged.gds
  - sky130_sram_1kbyte_1rw1r_32x256_8.lef
  - sky130_sram_2kbyte_1rw1r_32x512_8.lef
  - rules.svrf

commands:
  - echo "{caravel_path}"
  - echo "{design_name}"
  - cat "{caravel_path}"/verilog/gl/user_project_wrapper.v "{caravel_path}"/verilog/gl/user_proj_example.v > outputs/design.lvs.v
  - git clone https://github.com/CansWang/skywater-closed-pdk-flow.git
  - cp "{caravel_path}"/gds/user_project_wrapper.gds ./skywater-closed-pdk-flow/CDS/design.gds
  - cd skywater-closed-pdk-flow/CDS/
  - strmin -library strim -strmFile design.gds -logFile strmIn.log -topCell "{design_name}" -view layout -case Preserve -layerMap /skywater/V2.1.302/LIBS/S130/S8_to_S130.layermap -propSeparator , -attachTechFileOfLib S130
  - strmout -library strim -strmFile design_merged.gds -logFile strmOut.log -topCell "{design_name}" -view layout -case Preserve -layerMap /skywater/V2.1.302/LIBS/S130/S130.layermap -techLib S130 -convertDot node -convertPcellPin geometry
  - cd ../../
  - mv ./skywater-closed-pdk-flow/CDS/design_merged.gds ./outputs/design_merged.gds
  - cp "{sram_path}"/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.lef sky130_sram_2kbyte_1rw1r_32x512_8.lef
  - cp "{sram_path}"/sky130_sram_1kbyte_1rw1r_32x256_8/sky130_sram_1kbyte_1rw1r_32x256_8.lef sky130_sram_1kbyte_1rw1r_32x256_8.lef


parameters:
  caravel_path: "/scratch/users/praina/ee372/gcdunit_caravel_user_project"
  sram_path: "/farmshare/home/classes/ee/372/PDKs/sky130_sram_macros"
  design_name: "user_project_wrapper"
