#=========================================================================
# LVS using netgen
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: netgen-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk # Needs netgen.tcl setup file from adk
  - design.extracted.spice
  - design.lvs.v

outputs:
  - lvs_results.log

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - sh run_lvs.sh

