#=========================================================================
# Extract spice from gds using magic
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: magic-gds2spice

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds

outputs:
  - design.extracted.spice

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
  - magic -noconsole -dnull extract.tcl | tee gds2spice.log
