#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - sram.sp
  - sram.v
  - sram.lef
  - sram_tt_1p1V_25C.lib
  - sram_tt_1p1V_25C.db
  - sram.gds

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.sp outputs/sram.sp
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.v outputs/sram.v
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.lef outputs/sram.lef
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib outputs/sram_tt_1p1V_25C.lib
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db outputs/sram_tt_1p1V_25C.db
  - cp /afs/ir.stanford.edu/class/ee272/skywater-openram/sky130_fd_bd_sram/macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.gds outputs/sram.gds

