name: testbench

inputs:
  - adk

outputs:
  - testbench.sv
  - design.args
  - design.args.gls

commands:
  - cp SramUnitTb.sv outputs/testbench.sv
  - cp design.args outputs/design.args
  - cat design.args.gls inputs/adk/vcs_incdir.txt > outputs/design.args.gls
