#=========================================================================
# DRC using magic
#=========================================================================
# Author : Priyanka Raina
# Date   : Dec 12, 2020
#

name: magic-drc

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------
inputs:
  - adk
  - design_merged.gds

outputs:

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined

commands: 
#  - magic inputs/adk/stdcells.gds/sky130_fd_sc_hd__inv_1.gds
  - magic inputs/design_merged.gds
